/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS02832;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author XXIVKVNGLRT
 */
public class FrmKRS extends javax.swing.JFrame {

    /**
     * Creates new form FrmLatih05
     */
    public FrmKRS() {
        initComponents();
        
         //menanambahkan title icon
         ImageIcon icon = new ImageIcon("assets/krs_icon.png");
            setIconImage(icon.getImage());
    }

    
     void filterangka(KeyEvent a){
        char karakter = a.getKeyChar();
        if(!(((karakter >= 'a') && (karakter <= 'z') || (karakter == KeyEvent.VK_BACK_SPACE)  || (karakter == KeyEvent.VK_SPACE)|| (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            a.consume();
            JOptionPane.showMessageDialog(null, "Inputan hanya Huruf saja", "Peringatan",1);
        }
                
    }
     
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtNIM = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        TxtPS = new javax.swing.JTextField();
        TxtSKS = new javax.swing.JTextField();
        TxtJadwal1 = new javax.swing.JTextField();
        CmbMatkul = new javax.swing.JComboBox<>();
        JComboKlmpk = new javax.swing.JComboBox<>();
        TxtJadwal2 = new javax.swing.JTextField();
        TxtJadwal3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtnBaru = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblKRS = new javax.swing.JTable();
        BtnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kartu Rencana Studi");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("NIM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setText("Mata Kuliah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel6.setText("SKS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel7.setText("Kelompok");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel8.setText("Jadwal 1");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel9.setText("Jadwal 2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel10.setText("Jadwal 3");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        TxtNIM.setEnabled(false);
        TxtNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtNIMFocusLost(evt);
            }
        });
        TxtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNIMActionPerformed(evt);
            }
        });
        TxtNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNIMKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNIMKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNIMKeyTyped(evt);
            }
        });
        getContentPane().add(TxtNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 400, -1));

        TxtNama.setEnabled(false);
        TxtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaActionPerformed(evt);
            }
        });
        TxtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNamaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNamaKeyTyped(evt);
            }
        });
        getContentPane().add(TxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 600, -1));

        TxtPS.setEnabled(false);
        getContentPane().add(TxtPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 360, -1));

        TxtSKS.setEnabled(false);
        getContentPane().add(TxtSKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 60, -1));

        TxtJadwal1.setEnabled(false);
        getContentPane().add(TxtJadwal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 770, -1));

        CmbMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Mata Kuliah---", "PBO I", "Basis Data Lanjut", "Pemprograman GIS", "Pemprograman Mobile I", "Pendidikan Agama", "Pendidikan Kewarganegaraan", "Dasar Kewirausahaan" }));
        CmbMatkul.setEnabled(false);
        CmbMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbMatkulActionPerformed(evt);
            }
        });
        CmbMatkul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbMatkulKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CmbMatkulKeyReleased(evt);
            }
        });
        getContentPane().add(CmbMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 210, -1));

        JComboKlmpk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Kelompok---", "A22.3301", "A22.3302" }));
        JComboKlmpk.setEnabled(false);
        JComboKlmpk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboKlmpkActionPerformed(evt);
            }
        });
        getContentPane().add(JComboKlmpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 160, -1));

        TxtJadwal2.setEnabled(false);
        getContentPane().add(TxtJadwal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 770, -1));

        TxtJadwal3.setEnabled(false);
        getContentPane().add(TxtJadwal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 770, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnBaru.setText("Add");
        BtnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBaruActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.setEnabled(false);
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResetMouseClicked(evt);
            }
        });
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancel");
        BtnCancel.setEnabled(false);
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        BtnKeluar.setText("Exit");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnBaru)
                .addGap(18, 18, 18)
                .addComponent(BtnReset)
                .addGap(18, 18, 18)
                .addComponent(BtnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 722, Short.MAX_VALUE)
                .addComponent(BtnKeluar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancel)
                    .addComponent(BtnReset)
                    .addComponent(BtnBaru)
                    .addComponent(BtnKeluar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1010, 50));

        jLabel12.setText("Program Studi");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Form KRS"));

        BtnSave.setText("Save");
        BtnSave.setEnabled(false);
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        TblKRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Program Studi", "Mata Kuliah", "SKS", "Kelompok", "Jadwal 1", "Jadwal 2", "Jadwal 3"
            }
        ));
        jScrollPane1.setViewportView(TblKRS);

        BtnDelete.setText("Delete");
        BtnDelete.setEnabled(false);
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnSave, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(BtnSave)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnDelete)
                .addGap(4, 4, 4))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1010, 570));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon("H:\\Mata Kuliah\\Semester 3\\Pemprograman Object Oriented 1\\Tugas\\Uas\\UAS02832\\assets\\btn_krs.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("KARTU RENCANA STUDI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(349, 349, 349))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(461, 461, 461))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1010, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBaruActionPerformed
        // TODO add your handling code here:
        TxtNIM.setEnabled(true);
        TxtNama.setEnabled(false);
        TxtPS.setEnabled(false);
        TxtSKS.setEnabled(false);
        CmbMatkul.setEnabled(false);
        JComboKlmpk.setEnabled(false);
        TxtJadwal1.setEnabled(false);
        TxtJadwal2.setEnabled(false);
        TxtJadwal3.setEnabled(false);
        BtnBaru.setEnabled(false);
        BtnCancel.setEnabled(true);
        BtnReset.setEnabled(false);
        BtnKeluar.setEnabled(true);
        
        TxtNIM.requestFocus(true);
    }//GEN-LAST:event_BtnBaruActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        
        TxtNama.setText("");
        TxtNIM.setText("");
        TxtPS.setText("");
        TxtSKS.setText("");
        TxtJadwal1.setText("");
        TxtJadwal2.setText("");
        TxtJadwal3.setText("");
        BtnSave.setEnabled(false);
        TxtNIM.setEnabled(true);
        TxtNama.setEnabled(false);
        TxtPS.setEnabled(false);
        TxtSKS.setEnabled(false);
        BtnReset.setEnabled(false);
        CmbMatkul.setEnabled(false);
        
        
        
        TxtJadwal1.setEnabled(false);
        TxtJadwal2.setEnabled(false);
        TxtJadwal3.setEnabled(false);
       
        BtnDelete.setEnabled(false);
        CmbMatkul.setSelectedIndex(0);
        JComboKlmpk.setSelectedIndex(0);
        JComboKlmpk.setEnabled(false);
        TxtNIM.requestFocus();
        
        
         DefaultTableModel dataModel = (DefaultTableModel) TblKRS.getModel();    
            if (TblKRS.getRowCount() > 0) {
                for (int i = TblKRS.getRowCount() - 1; i >= 0; i--) {
                    dataModel.removeRow(i);
                }
            }
            
        TxtNIM.requestFocus();
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        // TODO add your handling code here:
        
        TxtNIM.setEnabled(false);
        TxtNama.setEnabled(false);
        TxtPS.setEnabled(false);
        TxtSKS.setEnabled(false);
        TxtJadwal1.setEnabled(false);
        TxtJadwal2.setEnabled(false);
        TxtJadwal3.setEnabled(false);
        
     
        
        BtnBaru.setEnabled(true);
        BtnReset.setEnabled(false);
        BtnBaru.requestFocus();
        BtnCancel.setEnabled(false);
        BtnDelete.setEnabled(false);
        
        TxtNama.setText("");
        TxtNIM.setText("");
        TxtPS.setText("");
        TxtSKS.setText("");
        TxtJadwal1.setText("");
        TxtJadwal2.setText("");
        TxtJadwal3.setText("");
        CmbMatkul.setSelectedIndex(0);
        JComboKlmpk.setSelectedIndex(0);
        CmbMatkul.setEnabled(false);
        JComboKlmpk.setEnabled(false);
        BtnSave.setEnabled(false);
        
        DefaultTableModel dataModel = (DefaultTableModel) TblKRS.getModel();    
            if (TblKRS.getRowCount() > 0) {
                for (int i = TblKRS.getRowCount() - 1; i >= 0; i--) {
                    dataModel.removeRow(i);
                }
            }
        
        
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void TxtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNIMActionPerformed
        // TODO add your handling code here:
         String temp = TxtNIM.getText();
        String kode = (temp.substring(0,3));
        
        if (kode.equalsIgnoreCase("A11")) {
            TxtPS.setText("Teknik Infromatika S1");
        } else if (kode.equalsIgnoreCase("A22")){
            TxtPS.setText("Teknik Informatika D3");
        }  else if (kode.equalsIgnoreCase("A14")) {
        TxtPS.setText("Desain Komunikasi Visual S1");
        } else if (kode.equalsIgnoreCase("A12")) {
        TxtPS.setText("Sistem Informasi S1");
        } else if (kode.equalsIgnoreCase("A15")) {
        TxtPS.setText("Ilmu Komunikasi S1");
        } else if (kode.equalsIgnoreCase("A16")) {
        TxtPS.setText("Produksi Film Televisi D4");
        } else if (kode.equalsIgnoreCase("A17")) {
        TxtPS.setText("Animasi D4");
        } else {
            TxtNIM.requestFocus();
            
            JOptionPane.showMessageDialog(null, "Program Studi Tidak ditemukan !","Kesalahan", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            return;
            
        }
        TxtNama.setEnabled(true);
        TxtNama.requestFocus(true);
         
    }//GEN-LAST:event_TxtNIMActionPerformed

    private void TxtNIMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNIMKeyTyped
        // TODO add your handling code here:
        BtnReset.setEnabled(true);
        
     
    }//GEN-LAST:event_TxtNIMKeyTyped

    private void TxtNIMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNIMKeyPressed
        // TODO add your handling code here:
       
      
    }//GEN-LAST:event_TxtNIMKeyPressed

    private void TxtNIMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNIMKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_TxtNIMKeyReleased

    private void TxtNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtNIMFocusLost
        // TODO add your handling code here:
       
           
    }//GEN-LAST:event_TxtNIMFocusLost

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin keluar ?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
        this.dispose();
        }
        
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void TxtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaActionPerformed
        // TODO add your handling code here:
        
         CmbMatkul.setEnabled(true);
       
    }//GEN-LAST:event_TxtNamaActionPerformed

    private void TxtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyTyped
        // TODO add your handling code here:
         
         
    }//GEN-LAST:event_TxtNamaKeyTyped

    private void CmbMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbMatkulActionPerformed
        // TODO add your handling code here:
         JComboKlmpk.setEnabled(true);
        
        
        if (CmbMatkul.getSelectedIndex()==1) {
            TxtSKS.setText("4");
        } else if (CmbMatkul.getSelectedIndex()==2) {
            TxtSKS.setText("4");
        } else if (CmbMatkul.getSelectedIndex()==3) {
            TxtSKS.setText("4");
        } else if (CmbMatkul.getSelectedIndex()==4) {
            TxtSKS.setText("4");
        } else if (CmbMatkul.getSelectedIndex()==5) {
            TxtSKS.setText("2");
        } else if (CmbMatkul.getSelectedIndex()==6) {
            TxtSKS.setText("2");
        } else if (CmbMatkul.getSelectedIndex()==7) {
            TxtSKS.setText("2");
        } 
    }//GEN-LAST:event_CmbMatkulActionPerformed

    private void TxtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtNamaKeyPressed

    private void JComboKlmpkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboKlmpkActionPerformed
        // TODO add your handling code here:
        
        //Kelompok A22.3301
        if (JComboKlmpk.getSelectedIndex()==1 && CmbMatkul.getSelectedIndex()==1 ) {
            TxtJadwal1.setText("Senin, 12.30-14.10, D.5.5");
            TxtJadwal2.setText("Jumat, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Jumat, 12.30-14.10, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==1 && CmbMatkul.getSelectedIndex()==2) {
            TxtJadwal1.setText("Senin, 14.10-16.10, D.5.5");
            TxtJadwal2.setText("Senin, 16.20-18.00, D.5.5");
            TxtJadwal3.setText("Jumat, 14.10-16.20, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==1 && CmbMatkul.getSelectedIndex()==3) {
            TxtJadwal1.setText("Selasa, 08.40-10.20, D.5.5");
            TxtJadwal2.setText("Selasa, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Rabu, 12.30-14.10, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==1 && CmbMatkul.getSelectedIndex()==4) {
            TxtJadwal1.setText("Rabu, 08.40-10.20, D.5.5");
            TxtJadwal2.setText("Rabu, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Jumat, 08.40-10.20, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==1 && CmbMatkul.getSelectedIndex()==5) {
            TxtJadwal1.setText("Kamis, 08.40-10.20, H.5.1");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        } else if (JComboKlmpk.getSelectedIndex()==1 && CmbMatkul.getSelectedIndex()==6) {
            TxtJadwal1.setText("Selasa, 12.30-14.10, AULA");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        } else if (JComboKlmpk.getSelectedIndex()==1 && CmbMatkul.getSelectedIndex()==7) {
            TxtJadwal1.setText("Senin, 10.20-12.00, AULA");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        }
        
        //kelompok A22.3302
        
        if (JComboKlmpk.getSelectedIndex()==2 && CmbMatkul.getSelectedIndex()==1 ) {
            TxtJadwal1.setText("Senin, 12.30-14.10, D.5.5");
            TxtJadwal2.setText("Jumat, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Jumat, 12.30-14.10, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==2 && CmbMatkul.getSelectedIndex()==2) {
            TxtJadwal1.setText("Senin, 14.10-16.10, D.5.5");
            TxtJadwal2.setText("Senin, 16.20-18.00, D.5.5");
            TxtJadwal3.setText("Jumat, 14.10-16.20, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==2 && CmbMatkul.getSelectedIndex()==3) {
            TxtJadwal1.setText("Selasa, 08.40-10.20, D.5.5");
            TxtJadwal2.setText("Selasa, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Rabu, 12.30-14.10, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==2 && CmbMatkul.getSelectedIndex()==4) {
            TxtJadwal1.setText("Rabu, 08.40-10.20, D.5.5");
            TxtJadwal2.setText("Rabu, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Jumat, 08.40-10.20, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==2 && CmbMatkul.getSelectedIndex()==5) {
            TxtJadwal1.setText("Kamis, 08.40-10.20, H.5.1");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        } else if (JComboKlmpk.getSelectedIndex()==2 && CmbMatkul.getSelectedIndex()==6) {
            TxtJadwal1.setText("Selasa, 12.30-14.10, AULA");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        } else if (JComboKlmpk.getSelectedIndex()==2 && CmbMatkul.getSelectedIndex()==7) {
            TxtJadwal1.setText("Senin, 10.20-12.00, AULA");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        }
        
        BtnSave.setEnabled(true);
        
    }//GEN-LAST:event_JComboKlmpkActionPerformed

    private void TxtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyReleased
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_TxtNamaKeyReleased

    private void CmbMatkulKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbMatkulKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CmbMatkulKeyReleased

    private void CmbMatkulKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbMatkulKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CmbMatkulKeyPressed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel datamodel = (DefaultTableModel) TblKRS.getModel();
        List list = new ArrayList<>();
        TblKRS.setAutoCreateColumnsFromModel(true);
        list.add( TxtNIM.getText());
        list.add(TxtNama.getText());
        list.add(TxtPS.getText());
        list.add(CmbMatkul.getSelectedItem());
        list.add(TxtSKS.getText());
        list.add(JComboKlmpk.getSelectedItem());
        list.add(TxtJadwal1.getText());
        list.add(TxtJadwal2.getText());
        list.add(TxtJadwal3.getText());
        datamodel.addRow(list.toArray());
        
        
        //menghapus inputan
        
        
        CmbMatkul.setSelectedIndex(0);
        TxtSKS.setText("");
        JComboKlmpk.setSelectedIndex(0);
        TxtJadwal1.setText("");
        TxtJadwal2.setText("");
        TxtJadwal3.setText("");
        
        //Disable textfield
       
        TxtNIM.setEnabled(true);
        TxtNama.setEnabled(true);
        CmbMatkul.requestFocus();
        
        BtnDelete.setEnabled(true);
        BtnSave.setEnabled(false);
        
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        
         int brs =0 , jmlbaris=0;
         
      
         DefaultTableModel dataModel = (DefaultTableModel) TblKRS.getModel();
         brs = TblKRS.getSelectedRow();
         
         if (brs>=0) {
            int opsi = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
             if (opsi == JOptionPane.YES_NO_OPTION) {
                 //menghapus satu baris dalam tabel
                 
                 dataModel.removeRow(brs);
                 jmlbaris = dataModel.getRowCount();
                 
             }
         }
        TxtNIM.requestFocus();
         
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseClicked
        // TODO add your handling code here:
        BtnSave.setEnabled(false);
    }//GEN-LAST:event_BtnResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKRS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBaru;
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSave;
    private javax.swing.JComboBox<String> CmbMatkul;
    private javax.swing.JComboBox<String> JComboKlmpk;
    private javax.swing.JTable TblKRS;
    private javax.swing.JTextField TxtJadwal1;
    private javax.swing.JTextField TxtJadwal2;
    private javax.swing.JTextField TxtJadwal3;
    private javax.swing.JTextField TxtNIM;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtPS;
    private javax.swing.JTextField TxtSKS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
