/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS02832;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;


/**
 *
 * @author XXIVKVNGLRT
 */
public class FrmLatih05 extends javax.swing.JFrame {

    /**
     * Creates new form FrmLatih05
     */
    public FrmLatih05() {
        initComponents();
    }

    
     void filterangka(KeyEvent a){
        char karakter = a.getKeyChar();
        if(!(((karakter >= 'a') && (karakter <= 'z') || (karakter == KeyEvent.VK_BACK_SPACE)  || (karakter == KeyEvent.VK_SPACE)|| (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            a.consume();
            JOptionPane.showMessageDialog(null, "Inputan hanya Huruf saja", "Peringatan",1);
        }
                
    }
     
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtNIM = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        TxtPS = new javax.swing.JTextField();
        TxtSKS = new javax.swing.JTextField();
        TxtJadwal1 = new javax.swing.JTextField();
        JComboMK = new javax.swing.JComboBox<>();
        JComboKlmpk = new javax.swing.JComboBox<>();
        TxtJadwal2 = new javax.swing.JTextField();
        TxtJadwal3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtnBaru = new javax.swing.JButton();
        BtnBersih = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kartu Rencana Studi");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Kartu Rencana Studi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel2.setText("NIM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 118, -1, -1));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 147, -1, -1));

        jLabel4.setText("Program Studi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 176, -1, -1));

        jLabel5.setText("Mata Kuliah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 208, -1, -1));

        jLabel6.setText("SKS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 243, -1, -1));

        jLabel7.setText("Kelompok");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 278, -1, -1));

        jLabel8.setText("Jadwal 1");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 318, -1, -1));

        jLabel9.setText("Jadwal 2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 371, -1, -1));

        jLabel10.setText("Jadwal 3");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        TxtNIM.setEnabled(false);
        TxtNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtNIMFocusLost(evt);
            }
        });
        TxtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNIMActionPerformed(evt);
            }
        });
        TxtNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNIMKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNIMKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNIMKeyTyped(evt);
            }
        });
        getContentPane().add(TxtNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 115, 338, -1));

        TxtNama.setEnabled(false);
        TxtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaActionPerformed(evt);
            }
        });
        TxtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNamaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNamaKeyTyped(evt);
            }
        });
        getContentPane().add(TxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 144, 338, -1));

        TxtPS.setEnabled(false);
        getContentPane().add(TxtPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 173, 338, -1));

        TxtSKS.setEnabled(false);
        getContentPane().add(TxtSKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 70, -1));

        TxtJadwal1.setEnabled(false);
        getContentPane().add(TxtJadwal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 315, 338, -1));

        JComboMK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Mata Kuliah---", "PBO I", "Basis Data Lanjut", "Pemprograman GIS", "Pemprograman Mobile I", "Pendidikan Agama", "Pendidikan Kewarganegaraan", "Dasar Kewirausahaan" }));
        JComboMK.setEnabled(false);
        JComboMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboMKActionPerformed(evt);
            }
        });
        JComboMK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JComboMKKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JComboMKKeyReleased(evt);
            }
        });
        getContentPane().add(JComboMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 205, 338, -1));

        JComboKlmpk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Kelompok---", "A22.3301", "A22.3302" }));
        JComboKlmpk.setEnabled(false);
        JComboKlmpk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboKlmpkActionPerformed(evt);
            }
        });
        getContentPane().add(JComboKlmpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 275, 160, -1));

        TxtJadwal2.setEnabled(false);
        getContentPane().add(TxtJadwal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 368, 338, -1));

        TxtJadwal3.setEnabled(false);
        getContentPane().add(TxtJadwal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 415, 338, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnBaru.setText("Baru");
        BtnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBaruActionPerformed(evt);
            }
        });

        BtnBersih.setText("Bersih");
        BtnBersih.setEnabled(false);
        BtnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBersihActionPerformed(evt);
            }
        });

        BtnBatal.setText("Batal");
        BtnBatal.setEnabled(false);
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(BtnBaru)
                .addGap(18, 18, 18)
                .addComponent(BtnBersih)
                .addGap(18, 18, 18)
                .addComponent(BtnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(BtnKeluar)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBatal)
                    .addComponent(BtnBersih)
                    .addComponent(BtnBaru)
                    .addComponent(BtnKeluar))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 468, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBaruActionPerformed
        // TODO add your handling code here:
        TxtNIM.setEnabled(true);
        TxtNama.setEnabled(false);
        TxtPS.setEnabled(false);
        TxtSKS.setEnabled(false);
        JComboMK.setEnabled(false);
        JComboKlmpk.setEnabled(false);
        TxtJadwal1.setEnabled(false);
        TxtJadwal2.setEnabled(false);
        TxtJadwal3.setEnabled(false);
        BtnBaru.setEnabled(false);
        BtnBatal.setEnabled(true);
        BtnBersih.setEnabled(true);
        BtnKeluar.setEnabled(true);
        
        TxtNIM.requestFocus(true);
    }//GEN-LAST:event_BtnBaruActionPerformed

    private void BtnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBersihActionPerformed
        // TODO add your handling code here:
        TxtNama.setText("");
        TxtNIM.setText("");
        TxtPS.setText("");
        TxtSKS.setText("");
        TxtJadwal1.setText("");
        TxtJadwal2.setText("");
        TxtJadwal3.setText("");
         TxtNIM.setEnabled(true);
        TxtNama.setEnabled(false);
        TxtPS.setEnabled(false);
        TxtSKS.setEnabled(false);
        JComboMK.setEnabled(false);
        
        TxtJadwal1.setEnabled(false);
        TxtJadwal2.setEnabled(false);
        TxtJadwal3.setEnabled(false);
        JComboMK.setSelectedIndex(0);
        JComboKlmpk.setSelectedIndex(0);
        JComboKlmpk.setEnabled(false);
        TxtNIM.requestFocus();
    }//GEN-LAST:event_BtnBersihActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        // TODO add your handling code here:
        
        TxtNIM.setEnabled(false);
        TxtNama.setEnabled(false);
        TxtPS.setEnabled(false);
        TxtSKS.setEnabled(false);
        TxtJadwal1.setEnabled(false);
        TxtJadwal2.setEnabled(false);
        TxtJadwal3.setEnabled(false);
        
     
        
        BtnBaru.setEnabled(true);
        BtnBersih.setEnabled(false);
        BtnBaru.requestFocus();
        BtnBatal.setEnabled(false);
        
        TxtNama.setText("");
        TxtNIM.setText("");
        TxtPS.setText("");
        TxtSKS.setText("");
        TxtJadwal1.setText("");
        TxtJadwal2.setText("");
        TxtJadwal3.setText("");
        JComboMK.setSelectedIndex(0);
        JComboKlmpk.setSelectedIndex(0);
        JComboMK.setEnabled(false);
        JComboKlmpk.setEnabled(false);
        
        
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void TxtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNIMActionPerformed
        // TODO add your handling code here:
         String temp = TxtNIM.getText();
        String kode = (temp.substring(0,3));
        
        if (kode.equalsIgnoreCase("A11")) {
            TxtPS.setText("Teknik Infromatika S1");
        } else if (kode.equalsIgnoreCase("A22")){
            TxtPS.setText("Teknik Informatika D3");
        }  else if (kode.equalsIgnoreCase("A14")) {
        TxtPS.setText("Desain Komunikasi Visual S1");
        } else if (kode.equalsIgnoreCase("A12")) {
        TxtPS.setText("Sistem Informasi S1");
        } else if (kode.equalsIgnoreCase("A15")) {
        TxtPS.setText("Ilmu Komunikasi S1");
        } else if (kode.equalsIgnoreCase("A16")) {
        TxtPS.setText("Produksi Film Televisi D4");
        } else if (kode.equalsIgnoreCase("A17")) {
        TxtPS.setText("Animasi D4");
        } else {
            TxtNIM.requestFocus();
            
            JOptionPane.showMessageDialog(null, "Program Studi Tidak ditemukan !","Kesalahan", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            return;
            
        }
        TxtNama.setEnabled(true);
        TxtNama.requestFocus(true);
         
    }//GEN-LAST:event_TxtNIMActionPerformed

    private void TxtNIMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNIMKeyTyped
        // TODO add your handling code here:
     
    }//GEN-LAST:event_TxtNIMKeyTyped

    private void TxtNIMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNIMKeyPressed
        // TODO add your handling code here:
       
      
    }//GEN-LAST:event_TxtNIMKeyPressed

    private void TxtNIMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNIMKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_TxtNIMKeyReleased

    private void TxtNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtNIMFocusLost
        // TODO add your handling code here:
       
           
    }//GEN-LAST:event_TxtNIMFocusLost

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin keluar ?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
        System.exit(0);
        }
        
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void TxtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaActionPerformed
        // TODO add your handling code here:
        
         JComboMK.setEnabled(true);
       
    }//GEN-LAST:event_TxtNamaActionPerformed

    private void TxtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyTyped
        // TODO add your handling code here:
         
         
    }//GEN-LAST:event_TxtNamaKeyTyped

    private void JComboMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboMKActionPerformed
        // TODO add your handling code here:
         JComboKlmpk.setEnabled(true);
        
        
        if (JComboMK.getSelectedIndex()==1) {
            TxtSKS.setText("4");
        } else if (JComboMK.getSelectedIndex()==2) {
            TxtSKS.setText("4");
        } else if (JComboMK.getSelectedIndex()==3) {
            TxtSKS.setText("4");
        } else if (JComboMK.getSelectedIndex()==4) {
            TxtSKS.setText("4");
        } else if (JComboMK.getSelectedIndex()==5) {
            TxtSKS.setText("2");
        } else if (JComboMK.getSelectedIndex()==6) {
            TxtSKS.setText("2");
        } else if (JComboMK.getSelectedIndex()==7) {
            TxtSKS.setText("2");
        } 
    }//GEN-LAST:event_JComboMKActionPerformed

    private void TxtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtNamaKeyPressed

    private void JComboKlmpkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboKlmpkActionPerformed
        // TODO add your handling code here:
        
        //Kelompok A22.3301
        if (JComboKlmpk.getSelectedIndex()==1 && JComboMK.getSelectedIndex()==1 ) {
            TxtJadwal1.setText("Senin, 12.30-14.10, D.5.5");
            TxtJadwal2.setText("Jumat, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Jumat, 12.30-14.10, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==1 && JComboMK.getSelectedIndex()==2) {
            TxtJadwal1.setText("Senin, 14.10-16.10, D.5.5");
            TxtJadwal2.setText("Senin, 16.20-18.00, D.5.5");
            TxtJadwal3.setText("Jumat, 14.10-16.20, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==1 && JComboMK.getSelectedIndex()==3) {
            TxtJadwal1.setText("Selasa, 08.40-10.20, D.5.5");
            TxtJadwal2.setText("Selasa, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Rabu, 12.30-14.10, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==1 && JComboMK.getSelectedIndex()==4) {
            TxtJadwal1.setText("Rabu, 08.40-10.20, D.5.5");
            TxtJadwal2.setText("Rabu, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Jumat, 08.40-10.20, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==1 && JComboMK.getSelectedIndex()==5) {
            TxtJadwal1.setText("Kamis, 08.40-10.20, H.5.1");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        } else if (JComboKlmpk.getSelectedIndex()==1 && JComboMK.getSelectedIndex()==6) {
            TxtJadwal1.setText("Selasa, 12.30-14.10, AULA");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        } else if (JComboKlmpk.getSelectedIndex()==1 && JComboMK.getSelectedIndex()==7) {
            TxtJadwal1.setText("Senin, 10.20-12.00, AULA");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        }
        
        //kelompok A22.3302
        
        if (JComboKlmpk.getSelectedIndex()==2 && JComboMK.getSelectedIndex()==1 ) {
            TxtJadwal1.setText("Senin, 12.30-14.10, D.5.5");
            TxtJadwal2.setText("Jumat, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Jumat, 12.30-14.10, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==2 && JComboMK.getSelectedIndex()==2) {
            TxtJadwal1.setText("Senin, 14.10-16.10, D.5.5");
            TxtJadwal2.setText("Senin, 16.20-18.00, D.5.5");
            TxtJadwal3.setText("Jumat, 14.10-16.20, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==2 && JComboMK.getSelectedIndex()==3) {
            TxtJadwal1.setText("Selasa, 08.40-10.20, D.5.5");
            TxtJadwal2.setText("Selasa, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Rabu, 12.30-14.10, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==2 && JComboMK.getSelectedIndex()==4) {
            TxtJadwal1.setText("Rabu, 08.40-10.20, D.5.5");
            TxtJadwal2.setText("Rabu, 10.20-12.00, D.5.5");
            TxtJadwal3.setText("Jumat, 08.40-10.20, D.5.5");
        } else if (JComboKlmpk.getSelectedIndex()==2 && JComboMK.getSelectedIndex()==5) {
            TxtJadwal1.setText("Kamis, 08.40-10.20, H.5.1");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        } else if (JComboKlmpk.getSelectedIndex()==2 && JComboMK.getSelectedIndex()==6) {
            TxtJadwal1.setText("Selasa, 12.30-14.10, AULA");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        } else if (JComboKlmpk.getSelectedIndex()==2 && JComboMK.getSelectedIndex()==7) {
            TxtJadwal1.setText("Senin, 10.20-12.00, AULA");
            TxtJadwal2.setText("-");
            TxtJadwal3.setText("-");
        }
    }//GEN-LAST:event_JComboKlmpkActionPerformed

    private void TxtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyReleased
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_TxtNamaKeyReleased

    private void JComboMKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JComboMKKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JComboMKKeyReleased

    private void JComboMKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JComboMKKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JComboMKKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLatih05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLatih05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLatih05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLatih05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLatih05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBaru;
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnBersih;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JComboBox<String> JComboKlmpk;
    private javax.swing.JComboBox<String> JComboMK;
    private javax.swing.JTextField TxtJadwal1;
    private javax.swing.JTextField TxtJadwal2;
    private javax.swing.JTextField TxtJadwal3;
    private javax.swing.JTextField TxtNIM;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtPS;
    private javax.swing.JTextField TxtSKS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
