/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS02832;

/**
 *
 * @author XXIVKVNGLRT
 */
public class FrmMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form FrmLatih03
     */
    public FrmMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtAlamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CmbKota = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        BtnReset = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TxtKetKota = new javax.swing.JTextField();
        BtnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pendataan Siswa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BIODATA MAHASISWA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setText("NIM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 61, -1, -1));

        TxtNim.setEnabled(false);
        getContentPane().add(TxtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 58, 380, -1));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 99, -1, -1));

        TxtNama.setEnabled(false);
        getContentPane().add(TxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 96, 380, -1));

        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 137, -1, -1));

        TxtAlamat.setEnabled(false);
        getContentPane().add(TxtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 134, 380, -1));

        jLabel5.setText("Kota");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 175, -1, -1));

        CmbKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - KOTA - -", "SEMARANG", "KENDAL", "BATANG", "PEMALANG", "PEKALONGAN", "BREBES", "DEMAK", "KUDUS", "PATI" }));
        CmbKota.setEnabled(false);
        CmbKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbKotaActionPerformed(evt);
            }
        });
        getContentPane().add(CmbKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 172, -1, -1));

        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 214, -1, -1));

        jRadioButton1.setText("Laki-laki");
        jRadioButton1.setEnabled(false);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 210, -1, -1));

        jRadioButton2.setText("Perempuan");
        jRadioButton2.setEnabled(false);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 210, -1, -1));

        jLabel7.setText("Jurusan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 257, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - JURUSAN - -", "TEKNIK INFORMATIKA", "TEKNIK SIPIL", "HUKUM", "EKONOMI", "SASTRA INGGRIS", "SASTRA JEPANG", "SISTEM INFORMASI", "DKV", "ANIMASI", "ARSITEK" }));
        jComboBox3.setEnabled(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 251, -1, -1));

        BtnReset.setText("Reset");
        BtnReset.setEnabled(false);
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(BtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        jLabel8.setText("Ket Kota");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 50, 20));

        TxtKetKota.setEnabled(false);
        getContentPane().add(TxtKetKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 210, -1));

        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        CmbKota.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jRadioButton1.setSelected(false);
        TxtNim.setText("");
        CmbKota.setSelectedIndex(0);
        TxtNama.setText("");
        TxtAlamat.setText("");
        
        
    }//GEN-LAST:event_BtnResetActionPerformed

    private void CmbKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbKotaActionPerformed
        // TODO add your handling code here:
        if (CmbKota.getSelectedIndex()==1) {
            TxtKetKota.setText("Semarang");
        } else if (CmbKota.getSelectedIndex()==2) {
            TxtKetKota.setText("Kendal");
        } else if (CmbKota.getSelectedIndex()==3) {
            TxtKetKota.setText("Batang");
        } else  {
            TxtKetKota.setText("");
        }
    }//GEN-LAST:event_CmbKotaActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        TxtNim.setEnabled(true);
        TxtNama.setEnabled(true);
        TxtAlamat.setEnabled(true);
        CmbKota.setEnabled(true);
        BtnAdd.setEnabled(false);
        BtnReset.setEnabled(true);
        TxtNim.requestFocus();
        CmbKota.setEnabled(true);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jComboBox3.setEnabled(true);
        
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnReset;
    private javax.swing.JComboBox<String> CmbKota;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtKetKota;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNim;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
