/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS02832;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author XXIVKVNGLRT
 */
public class FrmMatkul extends javax.swing.JFrame {

    /**
     * Creates new form FrmDosen
     */
    public FrmMatkul() {
        initComponents();
        ImageIcon icon = new ImageIcon("assets/btn_matakuliah.png");
setIconImage(icon.getImage());


        
     
    }
    
    //filtehuruf
    void filterhuruf(KeyEvent a){
        char karakter = a.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_ENTER) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            a.consume();
            JOptionPane.showMessageDialog(null, "Inputan hanya Angka saja", "Peringatan",1);
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtKodeMatkul = new javax.swing.JTextField();
        TxtNamaMatkul = new javax.swing.JTextField();
        CmbSemester = new javax.swing.JComboBox<>();
        BtnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnHapus = new javax.swing.JButton();
        CmbSks = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblMatkul = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        BtnAdd = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Mata Kuliah");
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon("H:\\Mata Kuliah\\Semester 3\\Pemprograman Object Oriented 1\\Tugas\\Uas\\UAS02832\\assets\\iconmatakuliah.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MATA KULIAH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Mata Kuliah"));

        jLabel3.setText("Kode Mata Kuliah");

        jLabel4.setText("Nama Mata Kuliah");

        jLabel9.setText("Semester");

        TxtKodeMatkul.setEnabled(false);
        TxtKodeMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodeMatkulActionPerformed(evt);
            }
        });
        TxtKodeMatkul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtKodeMatkulKeyTyped(evt);
            }
        });

        TxtNamaMatkul.setEnabled(false);
        TxtNamaMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaMatkulActionPerformed(evt);
            }
        });

        CmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Semester--", "1", "2", "3", "4", "5", "6", "7", "8" }));
        CmbSemester.setEnabled(false);
        CmbSemester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbSemesterMouseClicked(evt);
            }
        });
        CmbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSemesterActionPerformed(evt);
            }
        });

        BtnSave.setText("Save");
        BtnSave.setEnabled(false);
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        jLabel5.setText("SKS");

        BtnHapus.setText("Delete");
        BtnHapus.setEnabled(false);
        BtnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHapusMouseClicked(evt);
            }
        });
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        CmbSks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SKS--", "1", "2", "3", "4", "5" }));
        CmbSks.setEnabled(false);
        CmbSks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSksActionPerformed(evt);
            }
        });

        TblMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Mata Kuliah", "Nama Mata Kuliah", "SKS", "Semester"
            }
        ));
        jScrollPane1.setViewportView(TblMatkul);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtKodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CmbSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSave, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnHapus, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtKodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtNamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CmbSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(BtnSave)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHapus)
                .addGap(260, 260, 260))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.setEnabled(false);
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancel");
        BtnCancel.setEnabled(false);
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAdd)
                .addGap(18, 18, 18)
                .addComponent(BtnReset)
                .addGap(18, 18, 18)
                .addComponent(BtnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExit)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdd)
                    .addComponent(BtnReset)
                    .addComponent(BtnCancel)
                    .addComponent(BtnExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        TxtKodeMatkul.setEnabled(true);
        TxtKodeMatkul.requestFocus();
        BtnAdd.setEnabled(false);
        BtnCancel.setEnabled(true);
        
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
         String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin keluar ?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
        this.dispose();
        }
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        
        //membersihkan inputan
        
        TxtNamaMatkul.setText("");
        TxtKodeMatkul.setText("");
        btngroup.clearSelection();
        CmbSemester.setSelectedIndex(0);
       
        
        
        //menonaktifkan inputan txt
        
        TxtKodeMatkul.setEnabled(true);
        TxtNamaMatkul.setEnabled(false);
        BtnReset.setEnabled(false);
       BtnSave.setEnabled(false);
        CmbSemester.setEnabled(false);
       
        
         DefaultTableModel dataModel = (DefaultTableModel) TblMatkul.getModel();    
            if (TblMatkul.getRowCount() > 0) {
                for (int i = TblMatkul.getRowCount() - 1; i >= 0; i--) {
                    dataModel.removeRow(i);
                }
            }
            
        TxtKodeMatkul.requestFocus();
                
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        // TODO add your handling code here:
           //membersihkan inputan
        
        TxtNamaMatkul.setText("");
        TxtKodeMatkul.setText("");
        btngroup.clearSelection();
        CmbSemester.setSelectedIndex(0);
        
        
        
        // mematikan inputan
        
        TxtKodeMatkul.setEnabled(false);
        TxtNamaMatkul.setEnabled(false);
        BtnSave.setEnabled(true);
        BtnCancel.setEnabled(true);
        CmbSemester.setEnabled(false);
        BtnReset.setEnabled(false);
        BtnSave.setEnabled(false);
        BtnHapus.setEnabled(false);
        BtnCancel.setEnabled(false);
        BtnAdd.setEnabled(true);
        
         DefaultTableModel dataModel = (DefaultTableModel) TblMatkul.getModel();    
            if (TblMatkul.getRowCount() > 0) {
                for (int i = TblMatkul.getRowCount() - 1; i >= 0; i--) {
                    dataModel.removeRow(i);
                }
            }
            
         BtnAdd.requestFocus();
            
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void CmbSksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSksActionPerformed
        // TODO add your handling code here:
        CmbSemester.setEnabled(true);
        CmbSemester.requestFocus();
    }//GEN-LAST:event_CmbSksActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        int brs =0 , jmlbaris=0;

        DefaultTableModel dataModel = (DefaultTableModel) TblMatkul.getModel();
        brs = TblMatkul.getSelectedRow();

        if (brs>=0) {
            int opsi = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
            if (opsi == JOptionPane.YES_NO_OPTION) {
                //menghapus satu baris dalam tabel

                dataModel.removeRow(brs);
                jmlbaris = dataModel.getRowCount();

            }
        }
        BtnReset.setEnabled(false);

    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHapusMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_BtnHapusMouseClicked

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:

        DefaultTableModel datamodel = (DefaultTableModel) TblMatkul.getModel();
        List list = new ArrayList<>();
        TblMatkul.setAutoCreateColumnsFromModel(true);
        list.add( TxtKodeMatkul.getText());
        list.add(TxtNamaMatkul.getText());
        list.add(CmbSks.getSelectedIndex());
        list.add( CmbSemester.getSelectedItem());
        datamodel.addRow(list.toArray());

        //Membersihkan data
        TxtKodeMatkul.setText("");
        TxtNamaMatkul.setText("");
        CmbSks.setSelectedIndex(0);
        CmbSemester.setSelectedIndex(0);

        //Menonaktifkan inputan
        TxtKodeMatkul.setEnabled(true);
        TxtNamaMatkul.setEnabled(false);
        CmbSemester.setEnabled(false);
        BtnHapus.setEnabled(true);
        BtnSave.setEnabled(false);
        CmbSks.setEnabled(false);
        TxtKodeMatkul.requestFocus();

    }//GEN-LAST:event_BtnSaveActionPerformed

    private void CmbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSemesterActionPerformed
        // TODO add your handling code here:
        BtnSave.setEnabled(true);
        BtnSave.requestFocus();

    }//GEN-LAST:event_CmbSemesterActionPerformed

    private void CmbSemesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbSemesterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbSemesterMouseClicked

    private void TxtNamaMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaMatkulActionPerformed
        // TODO add your handling code here:
        CmbSks.setEnabled(true);
        CmbSks.requestFocus();

    }//GEN-LAST:event_TxtNamaMatkulActionPerformed

    private void TxtKodeMatkulKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKodeMatkulKeyTyped
        // TODO add your handling code here:
        BtnReset.setEnabled(true);
        BtnCancel.setEnabled(true);
    }//GEN-LAST:event_TxtKodeMatkulKeyTyped

    private void TxtKodeMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodeMatkulActionPerformed
        // TODO add your handling code here:
        TxtNamaMatkul.setEnabled(true);
        TxtNamaMatkul.requestFocus();
    }//GEN-LAST:event_TxtKodeMatkulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMatkul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSave;
    private javax.swing.JComboBox<String> CmbSemester;
    private javax.swing.JComboBox<String> CmbSks;
    private javax.swing.JTable TblMatkul;
    private javax.swing.JTextField TxtKodeMatkul;
    private javax.swing.JTextField TxtNamaMatkul;
    private javax.swing.ButtonGroup btngroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
