/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS02832;

import javax.swing.JOptionPane;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.util.List;
import javax.swing.ImageIcon;
/**
 *
 * @author XXIVKVNGLRT
 */
public class FrmTranskip extends javax.swing.JFrame {

    /**
     * Creates new form FrmLatih06
     */
    public FrmTranskip() {
        initComponents();
        
         //menanambahkan title icon
         ImageIcon icon = new ImageIcon("assets/btn_transkip.png");
            setIconImage(icon.getImage());
    }

    
    
    public void hitung () {
      
      
    }
    
    void filterhuruf(KeyEvent a){
        char karakter = a.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_ENTER) || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            a.consume();
            JOptionPane.showMessageDialog(null, "Inputan hanya Angka saja", "Peringatan",1);
        }
                
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtNim = new javax.swing.JTextField();
        TxtPS = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        TxtSKSTOTAL = new javax.swing.JTextField();
        TxtIPS = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        JCMBMK = new javax.swing.JComboBox<>();
        TxtSKS = new javax.swing.JTextField();
        BtnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelMhs = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        TxtKodeMatkul = new javax.swing.JTextField();
        CmbNilai = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        BtnBaru = new javax.swing.JButton();
        BtnBersih = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transkip Nilai");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("NIM");

        jLabel2.setText("Program Studi");

        jLabel3.setText("Nama");

        jLabel4.setText("Total SKS");

        jLabel5.setText("IPK");

        TxtNim.setEnabled(false);
        TxtNim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtNimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtNimFocusLost(evt);
            }
        });
        TxtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNimActionPerformed(evt);
            }
        });
        TxtNim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNimKeyTyped(evt);
            }
        });

        TxtPS.setEnabled(false);

        TxtNama.setEnabled(false);
        TxtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaActionPerformed(evt);
            }
        });
        TxtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNamaKeyReleased(evt);
            }
        });

        TxtSKSTOTAL.setEnabled(false);

        TxtIPS.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtPS, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtSKSTOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(TxtIPS)))
                    .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TxtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtSKSTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtIPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(55, 55, 55))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setText("Mata Kuliah");

        jLabel7.setText("SKS");

        jLabel13.setText("Nilai");

        BtnTambah.setText("Save");
        BtnTambah.setEnabled(false);
        BtnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnTambahMouseClicked(evt);
            }
        });
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        JCMBMK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Mata Kuliah---", "PBO I", "Basis Data Lanjut", "Pemprograman GIS", "Pemprograman Mobile I", "Pendidikan Agama", "Pendidikan Kewarganegaraan", "Dasar Kewirausahaan" }));
        JCMBMK.setEnabled(false);
        JCMBMK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCMBMKItemStateChanged(evt);
            }
        });
        JCMBMK.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JCMBMKMouseDragged(evt);
            }
        });
        JCMBMK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCMBMKFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JCMBMKFocusLost(evt);
            }
        });
        JCMBMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCMBMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JCMBMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JCMBMKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JCMBMKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JCMBMKMouseReleased(evt);
            }
        });
        JCMBMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCMBMKActionPerformed(evt);
            }
        });
        JCMBMK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JCMBMKKeyPressed(evt);
            }
        });

        TxtSKS.setText(" ");
        TxtSKS.setEnabled(false);

        BtnHapus.setText("Delete");
        BtnHapus.setEnabled(false);
        BtnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHapusMouseClicked(evt);
            }
        });

        TabelMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Mata Kuliah", "Nama Mata Kuliah", "SKS", "Nilai"
            }
        ));
        jScrollPane2.setViewportView(TabelMhs);

        jLabel16.setText("Kode Mata Kuliah");

        TxtKodeMatkul.setEnabled(false);

        CmbNilai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Nilai--", "A", "AB", "B", "BC", "C", "D", "E" }));
        CmbNilai.setEnabled(false);
        CmbNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbNilaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JCMBMK, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TxtKodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(52, 52, 52)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(CmbNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(BtnTambah)))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnHapus)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCMBMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTambah)
                    .addComponent(TxtKodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnHapus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnBaru.setText("Add");
        BtnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBaruActionPerformed(evt);
            }
        });

        BtnBersih.setText("Reset");
        BtnBersih.setEnabled(false);
        BtnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBersihActionPerformed(evt);
            }
        });

        BtnBatal.setText("Cancel");
        BtnBatal.setEnabled(false);
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        BtnKeluar.setText("Exit");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnBaru)
                .addGap(18, 18, 18)
                .addComponent(BtnBersih)
                .addGap(18, 18, 18)
                .addComponent(BtnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnKeluar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBersih)
                    .addComponent(BtnBaru)
                    .addComponent(BtnBatal)
                    .addComponent(BtnKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setIcon(new javax.swing.ImageIcon("H:\\Mata Kuliah\\Semester 3\\Pemprograman Object Oriented 1\\Tugas\\Uas\\UAS02832\\assets\\transkip_icon.png")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("TRANSKIP NILAI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(396, 396, 396))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(339, 339, 339))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBaruActionPerformed
        // TODO add your handling code here:
        
        TxtNim.setEnabled(true);
        TxtPS.setEnabled(false);
        TxtNama.setEnabled(false);
        TxtSKSTOTAL.setEnabled(false);
        TxtIPS.setEnabled(false);
        TxtNim.requestFocus();
        BtnBersih.setEnabled(true);
        BtnBatal.setEnabled(true);
        BtnBaru.setEnabled(false);
        
        
        
                
    }//GEN-LAST:event_BtnBaruActionPerformed

    private void BtnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBersihActionPerformed
        // TODO add your handling code here:
        
        //pada saat klik button bersih maka semua text field akan empty
        
        TxtNim.setText("");
        TxtPS.setText("");
        TxtNama.setText("");
        TxtSKSTOTAL.setText("");
        TxtIPS.setText("");
        JCMBMK.setSelectedIndex(0);
        TxtSKS.setText("");
       
        
        TxtNim.setEnabled(true);
        TxtPS.setEnabled(false);
        TxtNama.setEnabled(false);
        TxtSKSTOTAL.setEnabled(false);
        TxtIPS.setEnabled(false);
        JCMBMK.setEnabled(false);
        TxtSKS.setEnabled(false);
       
        BtnTambah.setEnabled(false);
        BtnHapus.setEnabled(false);
        CmbNilai.setEnabled(false);
        BtnBaru.setEnabled(false);
        TxtNim.requestFocus();
        
        
           DefaultTableModel dataModel = (DefaultTableModel) TabelMhs.getModel();    
            if (TabelMhs.getRowCount() > 0) {
                for (int i = TabelMhs.getRowCount() - 1; i >= 0; i--) {
                    dataModel.removeRow(i);
                }
            }
        
    }//GEN-LAST:event_BtnBersihActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        // TODO add your handling code here:
        
        JCMBMK.setSelectedIndex(0);
        TxtNim.setText("");
        TxtPS.setText("");
        TxtNama.setText("");
        TxtSKSTOTAL.setText("");
        TxtIPS.setText("");
        
        TxtSKS.setText("");
       
       
        
        TxtNim.setEnabled(false);
        TxtPS.setEnabled(false);
        TxtNama.setEnabled(false);
        CmbNilai.setEnabled(false);
        TxtSKSTOTAL.setEnabled(false);
        TxtIPS.setEnabled(false);
        JCMBMK.setEnabled(false);
        TxtSKS.setEnabled(false);
     
        BtnTambah.setEnabled(false);
        BtnHapus.setEnabled(false);
        BtnBaru.setEnabled(true);
        BtnBersih.setEnabled(false);
        BtnBatal.setEnabled(false);
        BtnBaru.requestFocus();
        
        
        
         DefaultTableModel dataModel = (DefaultTableModel) TabelMhs.getModel();    
            if (TabelMhs.getRowCount() > 0) {
                for (int i = TabelMhs.getRowCount() - 1; i >= 0; i--) {
                    dataModel.removeRow(i);
                }
            }
        
       
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        //pada saat klik button keluar
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin keluar ?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
        this.dispose();
        }
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void TxtNimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNimKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_TxtNimKeyTyped

    private void TxtNimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtNimFocusLost
        // TODO add your handling code here:
       
       
       
    }//GEN-LAST:event_TxtNimFocusLost

    private void TxtNimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtNimFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNimFocusGained

    private void TxtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtNamaKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
  
    }//GEN-LAST:event_formComponentShown

    private void TxtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNimActionPerformed
        // TODO add your handling code here:
          String temp = TxtNim.getText();
        String kode = (temp.substring(0,3));
        
        if (kode.equalsIgnoreCase("A11")) {
            TxtPS.setText("Teknik Infromatika S1");
        } else if (kode.equalsIgnoreCase("A22")){
            TxtPS.setText("Teknik Informatika D3");
        }  else if (kode.equalsIgnoreCase("A14")) {
        TxtPS.setText("Desain Komunikasi Visual S1");
        } else if (kode.equalsIgnoreCase("A12")) {
        TxtPS.setText("Sistem Informasi S1");
        } else if (kode.equalsIgnoreCase("A15")) {
        TxtPS.setText("Ilmu Komunikasi S1");
        } else if (kode.equalsIgnoreCase("A16")) {
        TxtPS.setText("Produksi Film Televisi D4");
        } else if (kode.equalsIgnoreCase("A17")) {
        TxtPS.setText("Animasi D4");
        } else {
            TxtNim.requestFocus();
            TxtNama.setEnabled(false);
            TxtNim.requestFocus();
            JOptionPane.showMessageDialog(null, "Program Studi Tidak ditemukan !","Kesalahan", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            return;
            
        }
          
        TxtNama.setEnabled(true);
        TxtNama.requestFocus();
    }//GEN-LAST:event_TxtNimActionPerformed

    private void TxtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaActionPerformed
        // TODO add your handling code here:
        JCMBMK.setEnabled(true);
        JCMBMK.requestFocus();
    }//GEN-LAST:event_TxtNamaActionPerformed

    private void BtnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHapusMouseClicked
        // TODO add your handling code here:

        int brs =0 , jmlbaris=0, skstotal=0, sks = 0;
        double bobot, bobotsks=0, bobottotal=0, ips;
        String huruf;
        DefaultTableModel dataModel = (DefaultTableModel) TabelMhs.getModel();
        brs = TabelMhs.getSelectedRow();

        if (brs>=0) {
            int opsi = JOptionPane.showConfirmDialog(null, "Yakin dihapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
            if (opsi == JOptionPane.YES_NO_OPTION) {
                //menghapus satu baris dalam tabel

                dataModel.removeRow(brs);
                jmlbaris = dataModel.getRowCount();
                if (jmlbaris<=0) {
                    TxtSKSTOTAL.setText("");
                    TxtIPS.setText("");
                }
                else {

                    //Menghitung ulang sks dan ips
                    jmlbaris= dataModel.getRowCount();
                    for (int i = 0; i < jmlbaris; i ++) {
                        //menghitung sks
                        sks = Integer.valueOf(dataModel.getValueAt(i,2).toString());
                        skstotal = skstotal + sks;

               
                       // menghitung ips
       
                    if (CmbNilai.getSelectedIndex()==1) 
                    {
                         bobot = 4.0;
                    }
                    else if (CmbNilai.getSelectedIndex()==2) 
                    {
                        bobot = 3.5;
                    }
                    else if (CmbNilai.getSelectedIndex()==3) 
                    {
                        bobot = 3.0;
                    }
                    else if (CmbNilai.getSelectedIndex()==4) 
                    {
                        bobot = 2.5;
                    }
                    else if (CmbNilai.getSelectedIndex()==5) 
                    {
                        bobot = 2.0;
                    }
                    else if (CmbNilai.getSelectedIndex()==6) 
                    {
                        bobot = 1.0;
                    }
                    else {
                        bobot =0.0;
                    }


                    bobotsks = bobot * sks;
                    bobottotal = bobottotal + bobotsks;

                }

                    TxtSKSTOTAL.setText(String.valueOf(skstotal));
                    ips = bobottotal / skstotal;
                    TxtIPS.setText(String.valueOf(ips));

                    }
                }
            }
    }//GEN-LAST:event_BtnHapusMouseClicked

    private void JCMBMKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCMBMKKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_JCMBMKKeyPressed

    private void JCMBMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCMBMKActionPerformed
        // TODO add your handling code here:
        int sks;
        if (JCMBMK.getSelectedIndex()==1) {
            TxtSKS.setText("4");
            TxtKodeMatkul.setText("A22.53311");

        } else if (JCMBMK.getSelectedIndex()==2) {
            TxtSKS.setText("4");
              TxtKodeMatkul.setText("A22.53314");
          
        } else if (JCMBMK.getSelectedIndex()==3) {
            TxtSKS.setText("4");
            TxtKodeMatkul.setText("A22.53412");
            
        } else if (JCMBMK.getSelectedIndex()==4) {
            TxtSKS.setText("4");
           TxtKodeMatkul.setText("A22.53413");

        } else if (JCMBMK.getSelectedIndex()==5) {
            TxtSKS.setText("2");
            TxtKodeMatkul.setText("N2017053");

        } else if (JCMBMK.getSelectedIndex()==6) {
            TxtSKS.setText("2");
             TxtKodeMatkul.setText("N201706");
             
        } else if (JCMBMK.getSelectedIndex()==7) {
            TxtSKS.setText("2");
             TxtKodeMatkul.setText("U201701");
        }
        CmbNilai.setEnabled(true);
        
    }//GEN-LAST:event_JCMBMKActionPerformed

    private void JCMBMKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCMBMKMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_JCMBMKMouseReleased

    private void JCMBMKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCMBMKMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_JCMBMKMousePressed

    private void JCMBMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCMBMKMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_JCMBMKMouseExited

    private void JCMBMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCMBMKMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_JCMBMKMouseEntered

    private void JCMBMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCMBMKMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_JCMBMKMouseClicked

    private void JCMBMKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCMBMKFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_JCMBMKFocusLost

    private void JCMBMKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCMBMKFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_JCMBMKFocusGained

    private void JCMBMKMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCMBMKMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_JCMBMKMouseDragged

    private void JCMBMKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCMBMKItemStateChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_JCMBMKItemStateChanged

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        // TODO add your handling code here:
        int skstotal=0, sks=0, jmlbaris=0;
        double bobot, bobotsks=0, bobottotal=0, ips;
        String huruf;

        // memasukkan ke dalam table

        DefaultTableModel datamodel = (DefaultTableModel) TabelMhs.getModel();
        List list = new ArrayList<>();
        TabelMhs.setAutoCreateColumnsFromModel(true);
        list.add(JCMBMK.getSelectedItem());
        list.add(TxtKodeMatkul.getText());
        list.add(TxtSKS.getText());
        list.add(CmbNilai.getSelectedItem());
        
        
        datamodel.addRow(list.toArray());

        // menghitung total sks dan ips
        jmlbaris= datamodel.getRowCount();
        for (int i = 0; i < jmlbaris; i ++) {
            //menghitung sks
            sks = Integer.valueOf(datamodel.getValueAt(i,2).toString());
            skstotal = skstotal + sks;

            // menghitung ips
      
            if (CmbNilai.getSelectedIndex()==1) 
            {
                 bobot = 4.0;
            }
            else if (CmbNilai.getSelectedIndex()==2) 
            {
                bobot = 3.5;
            }
            else if (CmbNilai.getSelectedIndex()==3) 
            {
                bobot = 3.0;
            }
            else if (CmbNilai.getSelectedIndex()==4) 
            {
                bobot = 2.5;
            }
            else if (CmbNilai.getSelectedIndex()==5) 
            {
                bobot = 2.0;
            }
            else if (CmbNilai.getSelectedIndex()==6) 
            {
                bobot = 1.0;
            }
            else {
                bobot =0.0;
            }

            
            bobotsks = bobot * sks;
            bobottotal = bobottotal + bobotsks;

        }

        TxtSKSTOTAL.setText(String.valueOf(skstotal));
        ips = bobottotal / skstotal;
        TxtIPS.setText(String.valueOf(ips));

        //membersihkan
        TxtSKS.setText("");
        TxtKodeMatkul.setText("");
       

        JCMBMK.setSelectedIndex(0);
        CmbNilai.setSelectedIndex(0);
        BtnHapus.setEnabled(true);
        TxtSKS.setEnabled(false);
        
        
      
        BtnTambah.setEnabled(false);
        CmbNilai.setEnabled(false);
        JCMBMK.requestFocus();
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTambahMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_BtnTambahMouseClicked

    private void CmbNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbNilaiActionPerformed
        // TODO add your handling code here:
        BtnTambah.setEnabled(true);
    }//GEN-LAST:event_CmbNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTranskip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTranskip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTranskip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTranskip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTranskip().setVisible(true);
            }
        });
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBaru;
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnBersih;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JComboBox<String> CmbNilai;
    private javax.swing.JComboBox<String> JCMBMK;
    private javax.swing.JTable TabelMhs;
    private javax.swing.JTextField TxtIPS;
    private javax.swing.JTextField TxtKodeMatkul;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNim;
    private javax.swing.JTextField TxtPS;
    private javax.swing.JTextField TxtSKS;
    private javax.swing.JTextField TxtSKSTOTAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
