/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS02832;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author XXIVKVNGLRT
 */
public class FrmTugas2_02832 extends javax.swing.JFrame {

    private double byr1;
     private DecimalFormat df = new DecimalFormat("#,###,##0");
     
     //validasi angka
      void filterhuruf(KeyEvent a){
        char karakter = a.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_ENTER) || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            a.consume();
            JOptionPane.showMessageDialog(null, "Inputan hanya Angka saja", "Peringatan",1);
        }
                
    }
    
     
    /**
     * Creates new form FrmTugas2_02832
     */
    public FrmTugas2_02832() {
        initComponents();
    }

 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        TXTTARIF = new javax.swing.JTextField();
        BTNTARIF = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TXTTARIFPERUNTUKAN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXTDAYA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BTNDAYA = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTBIAYAPERKWH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TXTBIAYABEBAN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXTKWHAWAL = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXTKWHAKHIR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BTNKWH = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TXTIDPELANGGAN = new javax.swing.JTextField();
        TXTKWHPEMAKAIAN = new javax.swing.JTextField();
        TXTNAMAPELANGGAN = new javax.swing.JTextField();
        TXTALAMATPELANGGAN = new javax.swing.JTextField();
        TXTBIAYAPEMAKAIAN = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TXTRUPIAHTOTALTAGIHAN = new javax.swing.JTextField();
        TXTRUPIAHPEMAKAIANLISTRIK = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TXTRUPIAHBAYAR = new javax.swing.JTextField();
        BTNBAYAR = new javax.swing.JButton();
        TXTRUPIAHPAJAKPENERANGAN = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TXTRUPIAHKEMBALIAN = new javax.swing.JTextField();
        TXTPPN = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BTNBARU = new javax.swing.JButton();
        BTNBATAL = new javax.swing.JButton();
        BTNBERSIH = new javax.swing.JButton();
        BTNKELUAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perhitungan Tagihan Listrik");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PERHITUNGAN TAGIHAN LISTRIK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTextField2.setText("jTextField2");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TXTTARIF.setEnabled(false);
        TXTTARIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTARIFActionPerformed(evt);
            }
        });
        TXTTARIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTTARIFKeyReleased(evt);
            }
        });

        BTNTARIF.setText("Tarif");
        BTNTARIF.setEnabled(false);
        BTNTARIF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNTARIFMouseClicked(evt);
            }
        });
        BTNTARIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTARIFActionPerformed(evt);
            }
        });

        jLabel12.setText("Tarif Peruntukan");

        TXTTARIFPERUNTUKAN.setEnabled(false);

        jLabel2.setText("ID Pelanggan");

        TXTDAYA.setEnabled(false);
        TXTDAYA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTDAYAKeyTyped(evt);
            }
        });

        jLabel3.setText("Nama Pelanggan");

        BTNDAYA.setText("Daya");
        BTNDAYA.setEnabled(false);
        BTNDAYA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDAYAActionPerformed(evt);
            }
        });

        jLabel4.setText("Alamat Pelanggan");

        jLabel13.setText("Biaya per KWH");

        jLabel5.setText("Tarif");

        TXTBIAYAPERKWH.setEnabled(false);

        jLabel6.setText("Daya");

        jLabel14.setText("Biaya Beban");

        jLabel7.setText("KWH Awal");

        TXTBIAYABEBAN.setEnabled(false);

        jLabel8.setText("Biaya Pemakaian");

        TXTKWHAWAL.setEnabled(false);
        TXTKWHAWAL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTKWHAWALKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTKWHAWALKeyTyped(evt);
            }
        });

        jLabel15.setText("KWH Akhir");

        jLabel10.setText("Rupiah Pemakaian Listrik");

        TXTKWHAKHIR.setEnabled(false);
        TXTKWHAKHIR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTKWHAKHIRKeyTyped(evt);
            }
        });

        jLabel9.setText("Rupiah Pajak Penerangan Jalan");

        BTNKWH.setText("KWH");
        BTNKWH.setEnabled(false);
        BTNKWH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKWHActionPerformed(evt);
            }
        });

        jLabel11.setText("Rupiah PPN");

        jLabel16.setText("KWH Pemakaian");

        TXTIDPELANGGAN.setEnabled(false);
        TXTIDPELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIDPELANGGANActionPerformed(evt);
            }
        });

        TXTKWHPEMAKAIAN.setEnabled(false);

        TXTNAMAPELANGGAN.setEnabled(false);
        TXTNAMAPELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNAMAPELANGGANActionPerformed(evt);
            }
        });

        TXTALAMATPELANGGAN.setEnabled(false);
        TXTALAMATPELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTALAMATPELANGGANActionPerformed(evt);
            }
        });

        TXTBIAYAPEMAKAIAN.setEnabled(false);

        jLabel17.setText("Rupiah Total Tagihan");

        TXTRUPIAHTOTALTAGIHAN.setEnabled(false);
        TXTRUPIAHTOTALTAGIHAN.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TXTRUPIAHTOTALTAGIHANInputMethodTextChanged(evt);
            }
        });
        TXTRUPIAHTOTALTAGIHAN.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TXTRUPIAHTOTALTAGIHANPropertyChange(evt);
            }
        });
        TXTRUPIAHTOTALTAGIHAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTRUPIAHTOTALTAGIHANKeyReleased(evt);
            }
        });

        TXTRUPIAHPEMAKAIANLISTRIK.setEnabled(false);

        jLabel18.setText("Rupiah Bayar");

        TXTRUPIAHBAYAR.setEnabled(false);
        TXTRUPIAHBAYAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRUPIAHBAYARActionPerformed(evt);
            }
        });
        TXTRUPIAHBAYAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTRUPIAHBAYARKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTRUPIAHBAYARKeyTyped(evt);
            }
        });

        BTNBAYAR.setText("Bayar");
        BTNBAYAR.setEnabled(false);
        BTNBAYAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNBAYARMouseClicked(evt);
            }
        });
        BTNBAYAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBAYARActionPerformed(evt);
            }
        });

        TXTRUPIAHPAJAKPENERANGAN.setEnabled(false);

        jLabel19.setText("Rupiah Kembalian");

        TXTRUPIAHKEMBALIAN.setEnabled(false);

        TXTPPN.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXTKWHAWAL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTDAYA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTTARIF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNTARIF)
                                    .addComponent(BTNDAYA))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTTARIFPERUNTUKAN))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TXTKWHAKHIR, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTBIAYAPERKWH, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNKWH))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(TXTBIAYABEBAN))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TXTKWHPEMAKAIAN, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))))))
                    .addComponent(TXTALAMATPELANGGAN)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TXTBIAYAPEMAKAIAN, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17))
                            .addComponent(TXTIDPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTNAMAPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TXTRUPIAHPEMAKAIANLISTRIK, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TXTRUPIAHPAJAKPENERANGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTRUPIAHBAYAR)
                            .addComponent(TXTRUPIAHKEMBALIAN)
                            .addComponent(TXTRUPIAHTOTALTAGIHAN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNBAYAR))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TXTPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(TXTRUPIAHKEMBALIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTIDPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTNAMAPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TXTALAMATPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TXTTARIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNTARIF)
                            .addComponent(jLabel12)
                            .addComponent(TXTTARIFPERUNTUKAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TXTDAYA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNDAYA)
                            .addComponent(jLabel13)
                            .addComponent(TXTBIAYAPERKWH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(TXTBIAYABEBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TXTKWHAWAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(TXTKWHAKHIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNKWH)
                            .addComponent(jLabel16)
                            .addComponent(TXTKWHPEMAKAIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TXTBIAYAPEMAKAIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(TXTRUPIAHTOTALTAGIHAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TXTRUPIAHPEMAKAIANLISTRIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(TXTRUPIAHBAYAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTNBAYAR)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(TXTRUPIAHPAJAKPENERANGAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TXTPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BTNBARU.setText("Baru");
        BTNBARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBARUActionPerformed(evt);
            }
        });

        BTNBATAL.setText("Batal");
        BTNBATAL.setEnabled(false);
        BTNBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBATALActionPerformed(evt);
            }
        });

        BTNBERSIH.setText("Bersih");
        BTNBERSIH.setEnabled(false);
        BTNBERSIH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBERSIHActionPerformed(evt);
            }
        });

        BTNKELUAR.setText("Keluar");
        BTNKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKELUARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNBARU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNBATAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNBERSIH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNKELUAR)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNBARU)
                    .addComponent(BTNBATAL)
                    .addComponent(BTNBERSIH)
                    .addComponent(BTNKELUAR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNBARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBARUActionPerformed
        // TODO add your handling code here:
        TXTIDPELANGGAN.setEnabled(true);
        BTNBATAL.setEnabled(true);
        BTNBERSIH.setEnabled(true);
        BTNBARU.setEnabled(false);
        TXTIDPELANGGAN.requestFocus();
    }//GEN-LAST:event_BTNBARUActionPerformed

    private void BTNKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKELUARActionPerformed
        // TODO add your handling code here:
         //pada saat klik button keluar
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin keluar ?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
        System.exit(0);
        }
    }//GEN-LAST:event_BTNKELUARActionPerformed

    private void TXTIDPELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIDPELANGGANActionPerformed
        // TODO add your handling code here:
        TXTNAMAPELANGGAN.setEnabled(true);
        TXTNAMAPELANGGAN.requestFocus();
    }//GEN-LAST:event_TXTIDPELANGGANActionPerformed

    private void TXTNAMAPELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNAMAPELANGGANActionPerformed
        // TODO add your handling code here:
        TXTALAMATPELANGGAN.setEnabled(true);
        TXTALAMATPELANGGAN.requestFocus();
    }//GEN-LAST:event_TXTNAMAPELANGGANActionPerformed

    private void TXTALAMATPELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTALAMATPELANGGANActionPerformed
        // TODO add your handling code here:
        TXTTARIF.setEnabled(true);
        TXTTARIF.requestFocus();
    }//GEN-LAST:event_TXTALAMATPELANGGANActionPerformed

    private void TXTTARIFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTTARIFKeyReleased
        // TODO add your handling code here:
        BTNTARIF.setEnabled(true);
       
    }//GEN-LAST:event_TXTTARIFKeyReleased

    private void BTNTARIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTARIFActionPerformed
        // TODO add your handling code here:
            
         String temp = TXTTARIF.getText();
        String kode = (temp.substring(0,2));
        
        
         if (kode.equalsIgnoreCase("R1")) {
            TXTTARIFPERUNTUKAN.setText("RUMAH TANGGA");
        } else if (kode.equalsIgnoreCase("B2")){
            TXTTARIFPERUNTUKAN.setText("BISNIS");
        }  else if (kode.equalsIgnoreCase("I3")) {
            TXTTARIFPERUNTUKAN.setText("INDUSTRI");
        } else if (kode.equalsIgnoreCase("P4")) {
            TXTTARIFPERUNTUKAN.setText("PUBLIK");
        } else if (kode.equalsIgnoreCase("S5")) {
            TXTTARIFPERUNTUKAN.setText("SOSIAL");
        } else {
            TXTTARIF.requestFocus();
            JOptionPane.showMessageDialog(null, "Tarif Tidak ditemukan !","Kesalahan", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            return;
            
        }
         TXTDAYA.setEnabled(true);
         TXTDAYA.requestFocus();
    }//GEN-LAST:event_BTNTARIFActionPerformed

    private void BTNTARIFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNTARIFMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BTNTARIFMouseClicked

    private void TXTTARIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTARIFActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_TXTTARIFActionPerformed

    private void TXTDAYAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDAYAKeyTyped
        // TODO add your handling code here:
        BTNDAYA.setEnabled(true);
        filterhuruf(evt);
    }//GEN-LAST:event_TXTDAYAKeyTyped

    private void BTNDAYAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDAYAActionPerformed
        // TODO add your handling code here:
        int a, beban1;
       a=Integer.parseInt(TXTDAYA.getText());
        if (a==450) {
            TXTBIAYAPERKWH.setText("500");
            TXTBIAYABEBAN.setText("5.000");
           
        } else if (a==900) {
            TXTBIAYAPERKWH.setText("1.000");
            TXTBIAYABEBAN.setText("10.000");
           
        } else if (a==1300) {
            TXTBIAYAPERKWH.setText("1.500");
            TXTBIAYABEBAN.setText("15.000");
        } else if (a==2200) {
            TXTBIAYAPERKWH.setText("2.500");
            TXTBIAYABEBAN.setText("25.000");
        }   else {
            TXTDAYA.requestFocus();
            JOptionPane.showMessageDialog(null, "Daya Tidak ditemukan !","Kesalahan", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            return;
            
        }
        TXTKWHAWAL.setEnabled(true);
        TXTKWHAWAL.requestFocus();
    }//GEN-LAST:event_BTNDAYAActionPerformed

    private void TXTKWHAWALKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTKWHAWALKeyReleased
        // TODO add your handling code here:
        TXTKWHAKHIR.setEnabled(true);
        
        
    }//GEN-LAST:event_TXTKWHAWALKeyReleased

    private void TXTKWHAKHIRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTKWHAKHIRKeyTyped
        // TODO add your handling code here:
        BTNKWH.setEnabled(true);
        filterhuruf(evt);
    }//GEN-LAST:event_TXTKWHAKHIRKeyTyped

    private void BTNKWHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKWHActionPerformed
        // TODO add your handling code here:
        int a, b, beban, kwhpemakaian , biayapemakaian,kwh, f  ;
        double c, d, biayabeban, pajakpeneranganjalan, pemakaianlistrik, rupiahpemakaianlistrik, ppn,
                rupiahtotaltagihan;
          a=Integer.parseInt(TXTKWHAWAL.getText());
          b=Integer.parseInt(TXTKWHAKHIR.getText());
          c=Double.parseDouble(TXTBIAYAPERKWH.getText());
          d=Double.parseDouble(TXTBIAYABEBAN.getText());
       
         
          //menghitung kwh pemakaian
            kwhpemakaian = b - a;
            TXTKWHPEMAKAIAN.setText(String.valueOf(kwhpemakaian));
        
          
          // menghitung biaya pemakaian
          
       
      
            if (c==500) {
            kwh = 500;
            biayapemakaian = kwh * kwhpemakaian;
            TXTBIAYAPEMAKAIAN.setText(String.valueOf(biayapemakaian));
           
            } 
            else if (c==1.000) {
            kwh = 1000;
            biayapemakaian = kwh * kwhpemakaian;
            TXTBIAYAPEMAKAIAN.setText(String.valueOf(biayapemakaian));
           
        } 
            else if (c==1.500) {
            kwh = 1500;
            biayapemakaian = kwh * kwhpemakaian;
            TXTBIAYAPEMAKAIAN.setText(String.valueOf(biayapemakaian));
           
        } 
            else if (c==2.500) {
            kwh = 2500;
            biayapemakaian = kwh * kwhpemakaian;
            TXTBIAYAPEMAKAIAN.setText(String.valueOf(biayapemakaian));
           
        } 
            
          
            DecimalFormat df = new DecimalFormat("#,###,##0");
            
          
         //menghitung rupiah pemakaian listrik 
         
         if (d==5.000) {
            beban = 5000;
             f=Integer.parseInt(TXTBIAYAPEMAKAIAN.getText());
        
             pemakaianlistrik= beban + f;
            TXTRUPIAHPEMAKAIANLISTRIK.setText(df.format(pemakaianlistrik));
            
            
            //menghitung rupiah pajak penerangan jalan
            
             pajakpeneranganjalan = 0.08 * pemakaianlistrik;
         TXTRUPIAHPAJAKPENERANGAN.setText(df.format(pajakpeneranganjalan));
         
         // menghitung rupiah ppn
         ppn= 0.1 * pemakaianlistrik;
         TXTPPN.setText(df.format(ppn));
         
         // menghitung total tagihan
       rupiahtotaltagihan = pemakaianlistrik + pajakpeneranganjalan + ppn;
       TXTRUPIAHTOTALTAGIHAN.setText(String.valueOf(rupiahtotaltagihan));
         
        } else if (d==10.000) {
            beban = 10000;
            f=Integer.parseInt(TXTBIAYAPEMAKAIAN.getText());
            pemakaianlistrik= beban + f;
            TXTRUPIAHPEMAKAIANLISTRIK.setText(df.format(pemakaianlistrik));
            
             //menghitung rupiah pajak penerangan jalan
            
             pajakpeneranganjalan = 0.08 * pemakaianlistrik;
         TXTRUPIAHPAJAKPENERANGAN.setText(df.format(pajakpeneranganjalan));
         
           // menghitung rupiah ppn
        ppn= 0.1 * pemakaianlistrik;
         TXTPPN.setText(df.format(ppn));
         
         // menghitung total tagihan
       rupiahtotaltagihan = pemakaianlistrik + pajakpeneranganjalan + ppn;
       TXTRUPIAHTOTALTAGIHAN.setText(String.valueOf(rupiahtotaltagihan));
       
         
        } else if (d==15.000) {
            beban = 15000;
             f=Integer.parseInt(TXTBIAYAPEMAKAIAN.getText());
           
            pemakaianlistrik= beban + f;
            TXTRUPIAHPEMAKAIANLISTRIK.setText(df.format(pemakaianlistrik));
            
             //menghitung rupiah pajak penerangan jalan
            
             pajakpeneranganjalan = 0.08 * pemakaianlistrik;
         TXTRUPIAHPAJAKPENERANGAN.setText(df.format(pajakpeneranganjalan));
         
           // menghitung rupiah ppn
          ppn= 0.1 * pemakaianlistrik;
         TXTPPN.setText(df.format(ppn));
         
         // menghitung total tagihan
       rupiahtotaltagihan = pemakaianlistrik + pajakpeneranganjalan + ppn;
       TXTRUPIAHTOTALTAGIHAN.setText(String.valueOf(rupiahtotaltagihan));
         
        } else if (d==25.000) {
            
            beban = 25000;
             f=Integer.parseInt(TXTBIAYAPEMAKAIAN.getText());
           
            pemakaianlistrik= beban + f;
            TXTRUPIAHPEMAKAIANLISTRIK.setText(df.format(pemakaianlistrik));
            
             //menghitung rupiah pajak penerangan jalan
            
             pajakpeneranganjalan = 0.08 * pemakaianlistrik;
         TXTRUPIAHPAJAKPENERANGAN.setText(df.format(pajakpeneranganjalan));
         
           // menghitung rupiah ppn
          ppn= 0.1 * pemakaianlistrik;
         TXTPPN.setText(df.format(ppn));
         
         // menghitung total tagihan
       rupiahtotaltagihan = pemakaianlistrik + pajakpeneranganjalan + ppn;
       TXTRUPIAHTOTALTAGIHAN.setText(String.valueOf(rupiahtotaltagihan));
            
        } 
         
      TXTRUPIAHBAYAR.setEnabled(true);
      TXTRUPIAHBAYAR.requestFocus();
         
         
         
         
    }//GEN-LAST:event_BTNKWHActionPerformed

    private void TXTRUPIAHBAYARKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTRUPIAHBAYARKeyReleased
        // TODO add your handling code here:
        BTNBAYAR.setEnabled(true);
      

        
    }//GEN-LAST:event_TXTRUPIAHBAYARKeyReleased

    private void BTNBAYARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNBAYARMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_BTNBAYARMouseClicked

    private void BTNBAYARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBAYARActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#,###,##0");
        //saat button bayar di klik
        double tagihan, bayar, rupiahkembalian;
         tagihan=Double.parseDouble(TXTRUPIAHTOTALTAGIHAN.getText().trim());
         bayar=Double.parseDouble(TXTRUPIAHBAYAR.getText().trim());
   
      
         //menghitung rupiah kembalian
         rupiahkembalian = bayar - tagihan;
         TXTRUPIAHKEMBALIAN.setText(df.format(rupiahkembalian));
    }//GEN-LAST:event_BTNBAYARActionPerformed

    private void TXTRUPIAHBAYARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRUPIAHBAYARActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_TXTRUPIAHBAYARActionPerformed

    private void TXTRUPIAHTOTALTAGIHANKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTRUPIAHTOTALTAGIHANKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TXTRUPIAHTOTALTAGIHANKeyReleased

    private void TXTRUPIAHTOTALTAGIHANPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TXTRUPIAHTOTALTAGIHANPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TXTRUPIAHTOTALTAGIHANPropertyChange

    private void TXTRUPIAHTOTALTAGIHANInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TXTRUPIAHTOTALTAGIHANInputMethodTextChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_TXTRUPIAHTOTALTAGIHANInputMethodTextChanged

    private void BTNBERSIHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBERSIHActionPerformed
        // TODO add your handling code here:
        TXTIDPELANGGAN.requestFocus();
        TXTIDPELANGGAN.setText("");
        TXTNAMAPELANGGAN.setText("");
        TXTALAMATPELANGGAN.setText("");
        TXTTARIF.setText("");
        TXTTARIFPERUNTUKAN.setText("");
        TXTDAYA.setText("");
        TXTBIAYAPERKWH.setText("");
        TXTBIAYABEBAN.setText("");
        TXTKWHAWAL.setText("");
        TXTKWHAKHIR.setText("");
        TXTKWHPEMAKAIAN.setText("");
        TXTBIAYAPEMAKAIAN.setText("");
        TXTRUPIAHPEMAKAIANLISTRIK.setText("");
        TXTRUPIAHTOTALTAGIHAN.setText("");
        TXTRUPIAHBAYAR.setText("");
        TXTRUPIAHPAJAKPENERANGAN.setText("");
        TXTRUPIAHKEMBALIAN.setText("");
        TXTPPN.setText("");
        
       
        TXTNAMAPELANGGAN.setEnabled(false);
        TXTALAMATPELANGGAN.setEnabled(false);
        TXTTARIF.setEnabled(false);
        TXTTARIFPERUNTUKAN.setEnabled(false);
        TXTDAYA.setEnabled(false);
        TXTBIAYAPERKWH.setEnabled(false);
        TXTBIAYABEBAN.setEnabled(false);
        TXTKWHAWAL.setEnabled(false);
        TXTKWHAKHIR.setEnabled(false);
        TXTKWHPEMAKAIAN.setEnabled(false);
        TXTBIAYAPEMAKAIAN.setEnabled(false);
        TXTRUPIAHPEMAKAIANLISTRIK.setEnabled(false);
        TXTRUPIAHTOTALTAGIHAN.setEnabled(false);
        TXTRUPIAHBAYAR.setEnabled(false);
        TXTRUPIAHPAJAKPENERANGAN.setEnabled(false);
        TXTRUPIAHKEMBALIAN.setEnabled(false);
        TXTPPN.setEnabled(false);
        
        
        BTNTARIF.setEnabled(false);
        BTNDAYA.setEnabled(false);
        BTNBAYAR.setEnabled(false);
        BTNKWH.setEnabled(false);
    }//GEN-LAST:event_BTNBERSIHActionPerformed

    private void BTNBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBATALActionPerformed
        // TODO add your handling code here:
       
        TXTIDPELANGGAN.setText("");
        TXTNAMAPELANGGAN.setText("");
        TXTALAMATPELANGGAN.setText("");
        TXTTARIF.setText("");
        TXTTARIFPERUNTUKAN.setText("");
        TXTDAYA.setText("");
        TXTBIAYAPERKWH.setText("");
        TXTBIAYABEBAN.setText("");
        TXTKWHAWAL.setText("");
        TXTKWHAKHIR.setText("");
        TXTKWHPEMAKAIAN.setText("");
        TXTBIAYAPEMAKAIAN.setText("");
        TXTRUPIAHPEMAKAIANLISTRIK.setText("");
        TXTRUPIAHTOTALTAGIHAN.setText("");
        TXTRUPIAHBAYAR.setText("");
        TXTRUPIAHPAJAKPENERANGAN.setText("");
        TXTRUPIAHKEMBALIAN.setText("");
        TXTPPN.setText("");
        
       TXTIDPELANGGAN.setEnabled(false);
        TXTNAMAPELANGGAN.setEnabled(false);
        TXTALAMATPELANGGAN.setEnabled(false);
        TXTTARIF.setEnabled(false);
        TXTTARIFPERUNTUKAN.setEnabled(false);
        TXTDAYA.setEnabled(false);
        TXTBIAYAPERKWH.setEnabled(false);
        TXTBIAYABEBAN.setEnabled(false);
        TXTKWHAWAL.setEnabled(false);
        TXTKWHAKHIR.setEnabled(false);
        TXTKWHPEMAKAIAN.setEnabled(false);
        TXTBIAYAPEMAKAIAN.setEnabled(false);
        TXTRUPIAHPEMAKAIANLISTRIK.setEnabled(false);
        TXTRUPIAHTOTALTAGIHAN.setEnabled(false);
        TXTRUPIAHBAYAR.setEnabled(false);
        TXTRUPIAHPAJAKPENERANGAN.setEnabled(false);
        TXTRUPIAHKEMBALIAN.setEnabled(false);
        TXTPPN.setEnabled(false);
        
        
        BTNTARIF.setEnabled(false);
        BTNDAYA.setEnabled(false);
        BTNBAYAR.setEnabled(false);
        BTNKWH.setEnabled(false);
        
        BTNBARU.requestFocus();
        BTNBARU.setEnabled(true);
        BTNBATAL.setEnabled(false);
        BTNBARU.setEnabled(true);
        BTNBERSIH.setEnabled(false);
    }//GEN-LAST:event_BTNBATALActionPerformed

    private void TXTKWHAWALKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTKWHAWALKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
    }//GEN-LAST:event_TXTKWHAWALKeyTyped

    private void TXTRUPIAHBAYARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTRUPIAHBAYARKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
    }//GEN-LAST:event_TXTRUPIAHBAYARKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTugas2_02832.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTugas2_02832.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTugas2_02832.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTugas2_02832.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTugas2_02832().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBARU;
    private javax.swing.JButton BTNBATAL;
    private javax.swing.JButton BTNBAYAR;
    private javax.swing.JButton BTNBERSIH;
    private javax.swing.JButton BTNDAYA;
    private javax.swing.JButton BTNKELUAR;
    private javax.swing.JButton BTNKWH;
    private javax.swing.JButton BTNTARIF;
    private javax.swing.JTextField TXTALAMATPELANGGAN;
    private javax.swing.JTextField TXTBIAYABEBAN;
    private javax.swing.JTextField TXTBIAYAPEMAKAIAN;
    private javax.swing.JTextField TXTBIAYAPERKWH;
    private javax.swing.JTextField TXTDAYA;
    private javax.swing.JTextField TXTIDPELANGGAN;
    private javax.swing.JTextField TXTKWHAKHIR;
    private javax.swing.JTextField TXTKWHAWAL;
    private javax.swing.JTextField TXTKWHPEMAKAIAN;
    private javax.swing.JTextField TXTNAMAPELANGGAN;
    private javax.swing.JTextField TXTPPN;
    private javax.swing.JTextField TXTRUPIAHBAYAR;
    private javax.swing.JTextField TXTRUPIAHKEMBALIAN;
    private javax.swing.JTextField TXTRUPIAHPAJAKPENERANGAN;
    private javax.swing.JTextField TXTRUPIAHPEMAKAIANLISTRIK;
    private javax.swing.JTextField TXTRUPIAHTOTALTAGIHAN;
    private javax.swing.JTextField TXTTARIF;
    private javax.swing.JTextField TXTTARIFPERUNTUKAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
